# Generated by Django 2.0.3 on 2018-04-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='FirstSentiment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sessions',
            name='FirstStatement',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sessions',
            name='FirstTopic',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sessions',
            name='SecondSentiment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sessions',
            name='SecondStatement',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sessions',
            name='SecondTopic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
